#!/usr/bin/env python3
import re
import sys

pattern = '(.*):(.*)'
wellknown_community_set = {'local-as',
                           'no-advertise',
                           'no-export',
                           'internet',
                           'graceful-shutdown',
                           'accept-own',
                           'route-filter-translated-v4',
                           'route-filter-v4',
                           'route-filter-translated-v6',
                           'route-filter-v6',
                           'llgr-stale',
                           'no-llgr',
                           'accept-own-nexthop',
                           'blackhole',
                           'no-peer'}
if __name__ == '__main__':
    max_community = 65535
    min_community = 0
    if len(sys.argv) != 2:
        sys.exit(1)
    if sys.argv[1] in wellknown_community_set:
        sys.exit(0)
    if not re.match(pattern, sys.argv[1]):
        sys.exit(1)
    value = sys.argv[1].split(':')
    if not len(value) == 2:
        sys.exit(1)

    if (not value[0].isdigit()) or (not value[1].isdigit()):
        sys.exit(1)
    if int(value[0]) > max_community or int(value[0]) < min_community:
        exit(1)
    if int(value[1]) > max_community or int(value[1]) < min_community:
        exit(1)

    sys.exit(0)
