#!/usr/bin/env python3
import re
import sys

pattern = '(.*):(.*)'
pattern_ip = '^(?:(?:2(?:[0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9])\.){3}(?:(?:2([0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9]))$'
if __name__ == '__main__':
    max_2_octet_community = 65535
    max_4_octet_community = 4294967295
    min_community = 0

    if len(sys.argv) != 2:
        sys.exit(1)
    if not re.match(pattern, sys.argv[1]):
        sys.exit(1)
    value = sys.argv[1].split(':')

    if not len(value) == 2:
        sys.exit(1)

    if not value[1].isdigit():
        sys.exit(1)

    if re.match(pattern_ip, value[0]) and (
            int(value[1]) >= min_community and int(
            value[1]) <= max_2_octet_community):
        sys.exit(0)

    if not value[0].isdigit():
        sys.exit(1)

    if (int(value[0]) >= min_community and int(
            value[0]) <= max_2_octet_community) and (
            int(value[1]) >= min_community and int(
            value[1]) <= max_4_octet_community):
        sys.exit(0)

    sys.exit(1)
