#!/usr/bin/env python3
import re
import sys

pattern = '([0-9]*):([0-9]*):([0-9].*)'

if __name__ == '__main__':
    max_community = 4294967295
    min_community = 0
    if len(sys.argv) != 2:
        sys.exit(1)
    if not re.match(pattern, sys.argv[1]):
        sys.exit(1)
    value = sys.argv[1].split(':')
    if not len(value) == 3:
        sys.exit(1)
    if (not value[0].isdigit()) \
            or (not value[1].isdigit()) or (not value[2].isdigit()):
        sys.exit(1)
    if int(value[0]) > max_community or int(value[0]) < min_community:
        exit(1)
    if int(value[1]) > max_community or int(value[1]) < min_community:
        exit(1)
    if int(value[2]) > max_community or int(value[2]) < min_community:
        exit(1)
    sys.exit(0)
